[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
git add netlify.toml
git commit -m "Fix Netlify build config - remove PostCSS plugin"
git push
